const AUTHACTIONTYPES = {
  LOADING: "LOADING",
  SIGNUP: "SIGNUP",
  LOGIN: "LOGIN",
  NOT_LOADING: "NOT_LOADING",
  LOGOUT: "LOGOUT",
};

const TODOACTIONTYPES = {
  GET_TODOS: "GET_TODOS",
  EDIT_TODO: "EDIT_TODO",
  DELETE_TODO: "DELETE_TODO",
  LOADING: "LOADING",
  NOT_LOADING: "NOT_LOADING",
  GET_TODOONPAGE: "GET_TODOONPAGE"
};

export { AUTHACTIONTYPES, TODOACTIONTYPES };
